FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
LABEL maintainer="whatsevenlyl@gmail.com"

SHELL ["/bin/bash", "--login", "-c"]

# #######################################################################################
# Read ME
# Set the proxy host. Change the IP and port in line 12-14
# #######################################################################################
# Proxy, commet line 11~13 if no proxy has been used
ARG USE_PROXY true
ARG PROXY_IP=172.31.178.234
ARG PROXY_PORT=7890
ARG PROXY=http://$PROXY_IP:$PROXY_PORT
ARG DISPLAY=$PROXY_IP:0.0
ENV HTTP_PROXY=$PROXY
ENV HTTPS_PROXY=$PROXY
# #######################################################################################
# #######################################################################################

# RUN apt update && apt install wget -y
RUN \
    sed -i "s/archive.ubuntu.com/mirrors.ustc.edu.cn/g" /etc/apt/sources.list && \
    sed -i "s/security.ubuntu.com/mirrors.ustc.edu.cn/g" /etc/apt/sources.list && \
    apt update && \
    apt install wget -y

# apt dependencis
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt install -y swig libblas-dev liblapack-dev sudo tmux git cmake libx11-dev libxft-dev bison gperf libglfw3-dev libxi-dev libxcursor-dev libxdamage-dev libxinerama-dev libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev gcc-9 gdb make gdb git cmake wget curl zip unzip tar python3 sudo libtool autoconf python3-distutils autoconf-archive net-tools proxychains4 libdbus-1-dev
RUN sed -i "s/socks.*/http $PROXY_IP $PROXY_PORT/g" /etc/proxychains4.conf && sed -i "s/#quiet.*/quiet_mode/g" /etc/proxychains4.conf &&\
    echo 'set completion-ignore-case On' >> ~/.inputrc && \
    echo "root:root" | chpasswd && \
    apt update && \
    apt install -y openssh-server vim && \
    echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && \
    service ssh restart
RUN sh -c "$(wget -e use_proxy=yes -e https_proxy=$PROXY -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.4/zsh-in-docker.sh)" -- \
    -p git \
    -p https://github.com/agkozak/zsh-z \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions \
    && \
    chsh -s $(which zsh) root

RUN echo "export LC_ALL=en_US.UTF-8" >> ~/.zshrc && \
    echo "export LANG=en_US.UTF-8" >> ~/.zshrc && \
    echo "export PATH=/usr/local/cuda/bin/:\${PATH}"  >> ~/.zshrc && \
    echo "export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH" >> ~/.zshrc && \
    echo "alias p=proxychains4"  >> ~/.zshrc && \
    echo "alias pp='export HTTP_PROXY=$PROXY && export HTTPS_PROXY=$PROXY'"  >> ~/.zshrc && \
    echo "unsetopt nomatch"  >> ~/.zshrc && \
    echo "DISPLAY=$DISPLAY"  >> ~/.zshrc

RUN cd /root/ && \
    git clone --recursive https://github.com/yilinliu77/NVDNet && \
    cd NVDNet && chmod +x install.sh && ./install.sh

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py310_23.5.2-0-Linux-x86_64.sh -O ~/miniconda.sh && /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    /opt/conda/condabin/conda init bash zsh && \
    echo "conda activate base" >> ~/.bashrc && echo "conda activate base" >> ~/.zshrc

RUN echo 'channels:' > /root/.condarc && \
    echo '  - defaults' >> /root/.condarc && \
    echo 'show_channel_urls: true' >> /root/.condarc && \
    echo 'remote_read_timeout_secs: 3000.0' >> /root/.condarc && \
    echo 'default_channels:' >> /root/.condarc && \
    echo '  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main' >> /root/.condarc && \
    echo '  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r' >> /root/.condarc && \
    echo '  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2' >> /root/.condarc && \
    echo 'custom_channels:' >> /root/.condarc && \
    echo '  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud' >> /root/.condarc && \
    echo '  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud' >> /root/.condarc && \
    echo '  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud' >> /root/.condarc && \
    echo '  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud' >> /root/.condarc && \
    echo '  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud' >> /root/.condarc && \
    echo '  pytorch-lts: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud' >> /root/.condarc && \
    echo '  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud' >> /root/.condarc && \
    echo '  deepmodeling: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/' >> /root/.condarc; \
    conda clean -i -y

RUN git pull && chmod +x install_python.sh && ./install_python.sh

EXPOSE 22 6100 6101 6102 15000 15001
CMD ["/usr/sbin/sshd", "-D"]